#!/bin/bash
# Stamp-IT brainswap  Copyright 2018 Stamp-IT Blockchain Solution inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute,
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
# BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

source "$(dirname "${BASH_SOURCE[0]}")/error.sh"
source "$(dirname "${BASH_SOURCE[0]}")/ssh.sh"
source "$(dirname "${BASH_SOURCE[0]}")/factomd-conf.sh"
source "$(dirname "${BASH_SOURCE[0]}")/factomd-status.sh"

# Uncomment the following line to turn on debugging
#set -x

# User tweakable values
CONF_PATH="/var/lib/docker/volumes/factom_keys/_data/factomd.conf"
# End of user tweakable values

function usage() {
	echo "Stamp-IT brainswap  Copyright 2018 Stamp-IT Blockchain Solution inc."
	echo
	echo "Uses OpenSSH to brainswap two factomd nodes."
	echo
	echo "Usage:"
	echo "       brainswap [--sudo] [--noswap] [user1@]node1[:port1] [user2@]node2[:port2]"
	echo
	echo "node1 MUST be an authority node"
	echo "node2 is usually not be an authority node"
	echo
	echo "Tip:"
	echo "   You can add a line in your factomd.conf to mark the place where the brainswap identity should be inserted."
	echo "   Just insert a line that reads (without quotation marks): \"; BRAINSWAP_ID_BELOW\""
	echo "   Otherwise the identity will be insert at the begining of [app] section"
	echo "Tip:"
	echo "   You can use a SSH jump box to connect to a node by prepending user@jumphost to the target node and separating them with comma"
	echo "   e.g.: brainswap user@jumphost,user@authoritynode user@jumphost,user@followernode"
}

SUDO1=
SUDO2=
NOSWAP=
BLOCK_DELAY=0

while [ "$1" != "" ]; do
	case "$1" in
	"--help")
		usage
		exit 0
		;;
	"--sudo")
		SUDO1=sudo
		SUDO2=sudo
		sudo1="--sudo"
		sudo2="--sudo"
		;;
	"--sudo1")
		SUDO1=sudo
		sudo1="--sudo"
		;;
	"--sudo2")
		SUDO2=sudo
		sudo2="--sudo"
		;;
	"--noswap")
		NOSWAP=1
		;;
	"--quiet")
		QUIET=1
		;;
	"--debug")
		set -x
		;;
	-*)
		echo "$0: Unknown parameter $1." >&2
		echo "$0 --help for help." >&2
		exit 2
		;;
	*)
		if [ -z "$node1" ]; then
			node1="$1"
		elif [ -z "$node2" ]; then
			node2="$1"
		else
			echo "$0: Too many parameters." >&2
			echo "$0 --help for help." >&2
			exit 2
		fi
		;;
	esac
	shift
done

[ "$QUIET" != 1 ] && echo "Stamp-IT brainswap for factomd" >&2

# Parameters looking good
if [ -z "$node1" -o -z "$node2" ]; then
	usage >&2
	exit 2
fi

# We do not want to brainswap a node with itself!
if [ "$node1" = "$node2" ]; then
	print_error_stack_exit "$node1 and $node2 are the same nodes, cannot brainswap."
fi

echo "This is a pre-alpha version of brainswap. You should not use it except to give feedback." >&2
exit 1


#########
# Accessing node 1 to obtain some informations...

# Command to login to node1
SSH1="do_ssh $node1"

# Make sure config is writable before any modification si done
ensure_factomd_conf_writable $sudo1 $node1

# Obtain config from node1
must_succeed 'node1_conf="$(get_factomd_conf $sudo1 $access_spec)"'
must_succeed 'extract_conf_keys node1 <<<"$node1_conf"'

# Ensure an identiy is in node1 config file
if [ -z "$node1_IdCId_line" -o -z "$node1_LSPrivK_line" -o -z "$node1_LSPubK_line" ]; then
	# Technically, we could do a brainswap, but it is probably not what is intended
	print_error_stack_exit "$node1 has incomplete identity set in factomd.conf."
fi

# Obtain factomd version from node1
VERSION1=$(get_factomd_version $node1)

# Obtain information about factomd from node1
get_factomd_details $node1 node1

# Ensure node1 is an authority node and operating
if [ "$node1_factomd_flags" != "A___" -a "$node1_factomd_flags" != "L___" ]; then
	# We could do a brainswap, but it is probably not what is intended
	print_error_stack_exit "$node1 is not an authority node (or in ignore mode) no need for brainswap ($node1_factomd_flags)."
fi

# Ensure there is no <nil> in the process list of node1
if [ "$node1_factomd_pl_stats" != "OKOKOK" ]; then
	print_error_stack_exit "$node1 process list is incomplete, there might be some network instability ($node1_factomd_pl_stats)."
fi

# Ensure $node1_factomd_minute is a number between 0 and 9
if [ 0 -le "$node1_factomd_minute" -a "$node1_factomd_minute" -le "9" ]; then
	# Here we are sure $node1_factomd_minute is a number
	true
else
	print_error_stack_exit "$node1 minute $node1_factomd_minute, is not a number."
fi

# Ensure $node1_factomd_nextheight is a block number
if ! echo "$node1_factomd_nextheight" | egrep -q "^[0-9]{5,7}$"; then
	print_error_stack_exit "$node1 next height $node1_factomd_nextheight does not look like a block number."
fi

# Ensure no brainswap is pending on node1
if [ "$node1_factomd_nextheight" -le "$node1_CAH" ]; then
	print_error_stack_exit "$node1 next height $node1_factomd_nextheight is not greater than config ChangeAcksHeight $node1_CAH (pending brainswap?)"
fi

# During minute 0 we cannot tell if the nodes are really following minutes, so we do not initiate a brainswap
if [ "$node1_factomd_minute" -eq "0" ]; then
	print_error_stack_exit "$node1 in minute 0, wait for one minute and try again."
fi

#########
# Accessing node 2 to obtain some informations...

# Command to login to node2
SSH2="do_ssh $node2"

# Make sure config is writable before any modification si done
ensure_factomd_conf_writable $sudo2 $node2

# Obtain config from node2
get_factomd_keys $sudo2 $node2 node2

# Ensure node1 and node 2 are on the same network
if [ "$node1_Net" != "$node2_Net" ]; then
	print_error_stack_exit "$node1 and $node2 are on two different networks, cannot brainswap."
fi

# Find the place where the new identity will be inserted in config file (CONF2_APPEND is a sed script)
if echo "$node2_conf" | grep -q -i '^[[:space:]]*;*[[:space:]]*BRAINSWAP_ID_BELOW'; then
	CONF2_APPEND='/^[[:space:]]*;*[[:space:]]*BRAINSWAP_ID_BELOW/a\'
else
	if echo "$node2_conf" | grep -q -i '^[[:space:]]*\[app\]'; then
		CONF2_APPEND='/^[[:space:]]*\[app\]/a\'
	else
		print_error_stack_exit "$node2 factomd.conf has neither [app] section nor commented line with BRAINSWAP_ID_BELOW."
	fi
fi

# For node2, we do not expect an Identity in config file (but there might be one, it's Ok)...
# ...but we ensure node1 and node 2 have not the same identity in their config files
if [ "$node1_IdCId" = "$node2_IdCId" ]; then
	print_error_stack_exit "$node1 and $node2 have the same identity in their config files. (Same node?)"
fi

[ "$QUIET" != 1 ] && echo "Getting factomd version from $node2..." >&2

# Obtain factomd version from node2
VERSION2=$(get_factomd_version $node2)

[ "$QUIET" != 1 ] && echo "Getting factomd details from $node2..." >&2

# Obtain information about factomd from node2
get_factomd_details $node2 node2

# Ensure node2 is ready for brainswap
if [ "$node2_factomd_flags" != "A___" -a "$node2_factomd_flags" != "L___" -a "$node2_factomd_flags" != "____" ]; then
	print_error_stack_exit "$0: $node2 is not ready for brainswap ($node2_factomd_flags)."
fi

# Ensure there is no <nil> in the process list of node2
if [ "$node2_factomd_pl_stats" != "OKOKOK" ]; then
	print_error_stack_exit "$0: $node2 process list is incomplete, there might be some network instability ($node2_factomd_pl_stats)."
fi

# Ensure $node2_factomd_minute is a number between 0 and 9
if [ 0 -le "$node2_factomd_minute" -a "$node2_factomd_minute" -le "9" ]; then
	# Here we are sure $node2_factomd_minute is a number
	true
else
	print_error_stack_exit "$0: $node2 minute $node2_factomd_minute, is not a number."
fi

# Ensure $node2_factomd_nextheight is a block number
if ! echo "$node2_factomd_nextheight" | egrep -q "^[0-9]{5,7}$"; then
	print_error_stack_exit "$0: $node2 next height $node2_factomd_nextheight does not seem to be a block number."
fi

# Ensure no brainswap is pending on node 2
if [ "$node2_factomd_nextheight" -le "$node2_CAH" ]; then
	print_error_stack_exit "$0: $node2 next height $node2_factomd_nextheight not greater than config ChangeAcksHeight $node2_CAH (pending brainswap?)"
fi

# Ensure node1 and node2 are on the same block height
if [ "$node1_factomd_nextheight" != "$node2_factomd_nextheight" ]; then
	print_error_stack_exit "$0: $node1 and $node2 are not on the same block (next: $node1_factomd_nextheight, $node2_factomd_nextheight) try again in a few seconds."
fi

# Ensure node1 and node2 are on the same minute
if [ "$node1_factomd_minute" != "$node2_factomd_minute" ]; then
	print_error_stack_exit "$0: $node1 and $node2 are not on the same minute ($node1_factomd_minute, $node2_factomd_minute) try again in a few seconds."
fi

# Calculate time before swap and ChangeAcksHeight
CHANGE_HEIGHT=$node1_factomd_nextheight
SWAP_WAIT=$((10 - $node1_factomd_minute))
if [ "$node1_factomd_minute" -eq 9 ]; then
	# If we are on minute 9, we are too close to next block, we wait for one more block
	SWAP_WAIT=$(($SWAP_WAIT + 10))
	CHANGE_HEIGHT=$(($CHANGE_HEIGHT + 1))
fi
# Add a delay of a few blocks?
CHANGE_HEIGHT=$(($CHANGE_HEIGHT + $BLOCK_DELAY))
SWAP_WAIT=$(($SWAP_WAIT + $BLOCK_DELAY * 10))

if [ "$VERSION1" = v6.1.1 -o "$VERSION1" = v6.1.1-rc1 -o "$VERSION1" = v6.2.1-rc1 ]; then
	# Brainswap is not supported on these versions
	print_error_stack_exit "$0: Brainswap not supported with factomd $VERSION1."
fi
CAH1="ChangeAcksHeight = $CHANGE_HEIGHT"
if [ "$VERSION2" = v6.1.1 -o "$VERSION2" = v6.1.1-rc1 -o "$VERSION2" = v6.2.1-rc1 ]; then
	# Brainswap is not supported on these versions
	print_error_stack_exit "$0: Brainswap not supported with factomd $VERSION2."
fi
CAH2="ChangeAcksHeight = $CHANGE_HEIGHT"

# Generating new factomd.conf for node1
NEWCONF1=$(echo "$node1_conf" | grep -i -v '^[[:space:]]*IdentityChainID' | grep -i -v '^[[:space:]]*LocalServerPrivKey' | grep -i -v '^[[:space:]]*LocalServerPublicKey' | grep -i -v '^[[:space:]]*ChangeAcksHeight')
NEWCONF1=$(echo "$NEWCONF1" | sed "$CONF1_APPEND
$node2_IdCId_line\\
$node2_LSPrivK_line\\
$node_LSPubK_line\\
$CAH1")

if [ "$?" != 0 ]; then
	# Maybe due to a bad factomd.conf
	print_error_stack_exit "$0: Error while generating new factomd.conf for node1, aborting."
fi

# Generating new factomd.conf for node2
NEWCONF2=$(echo "$node2_conf" | grep -i -v '^[[:space:]]*IdentityChainID' | grep -i -v '^[[:space:]]*LocalServerPrivKey' | grep -i -v '^[[:space:]]*LocalServerPublicKey' | grep -i -v '^[[:space:]]*ChangeAcksHeight')
NEWCONF2=$(echo "$NEWCONF2" | sed "$CONF2_APPEND
$node1_IdCId_line\\
$node1_LSPrivK_line\\
$node1_LSPubK_line\\
$CAH2")

if [ "$?" != 0 ]; then
	# Maybe due to a bad factomd.conf
	print_error_stack_exit "$0: Error while generating new factomd.conf for node2, aborting."
fi

####################
# Ready to initiate brainswap
if [ "$QUIET" != 1 ]; then
	echo "Ready to brainswap at block height $CHANGE_HEIGHT, in about $SWAP_WAIT minutes:" >&2
	echo "--------" >&2
	echo "Node1: $node1:" >&2
	echo -e "$node1_IdCId_line\n$node1_LSPrivK_line\n$node1_LSPubK_line" >&2
	echo "--------" >&2
	echo "Node2: $node2:" >&2
	echo -e "$node2_IdCId_line\n$node2_LSPrivK_line\n$node_LSPubK_line" >&2
	echo "--------" >&2
fi

if [ "$NOSWAP" = "1" ]; then
	echo $0: "--noswap specified, not brainswapping."
	exit 0
fi

# We change node2 first because it is better to have 2 authority nodes than none (factomd might detect this)
[ "$QUIET" != 1 ] && echo "Rewriting factomd.conf on $node2..." >&2

if ! echo "$NEWCONF2" | $SSH2 $SUDO2 sh -c '"cat >'"$CONF_PATH"'"'; then
	print_error_stack_exit "$0: Error overwriting $CONF_PATH on $node2, BRAINSWAP FAILED, you must check that config was not overwritten."
fi

[ "$QUIET" != 1 ] && echo "Rewriting factomd.conf on $node1..." >&2

if ! echo "$NEWCONF1" | $SSH1 $SUDO1 sh -c '"cat >'"$CONF_PATH"'"'; then
	print_error_stack_exit "$0: Error overwriting $CONF_PATH on $node1, BRAINSWAP FAILED, you must check that both nodes do not have the same identity."
fi

echo "Brainswap initiated successfully for block $CHANGE_HEIGHT, in about $SWAP_WAIT minutes"

exit 0
